# Generated by Django 2.0 on 2018-09-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=70)),
                ('Address', models.CharField(max_length=300)),
                ('Telephone', models.IntegerField(max_length=20)),
                ('Email', models.EmailField(max_length=50)),
                ('purpose', models.TextField(max_length=500)),
                ('checkin', models.TimeField(max_length=60)),
                ('checkout', models.TimeField(max_length=20)),
            ],
        ),
    ]
