# Generated by Django 2.0 on 2018-09-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sangaria', '0002_auto_20180913_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='checkin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='checkout',
            field=models.IntegerField(),
        ),
    ]
